stages:
- test
- build
- deploy

# test project:
#     stage: test
#     image: node:16
#     script:
#         - npm install
#         - npm test


build project:
    stage: build
    image: node:16
    script:
        - npm install --force
        - CI=false npm run build
    artifacts:
        paths:
           - build/ 

netlify:
    stage: deploy
    image: node:16
    script:
        - npm install -g netlify-cli
        -  netlify deploy --dir=build --prod